[package]
name = "smallpt"
version = "0.1.0"
authors = ["Jean d'Arc <darc.void@googlemail.com>"]
edition = "2018"

[[bin]]
name = "smallpt"
path = "smallpt.rs"

[dependencies]
rand = "0.8.0"
rayon = "1.5.0"
